### ISSUE TITLE
Brainstorm: Bindings for end of word

### ISSUE THREAD

**Issue by bmallred** [wbolster/evil-colemak-basics#2]
> an easy to reach 'end of word' (easy to reach ```e``` on qwerty, ```j``` on colemak with the package)

Non-issue but maybe throwing out some ideas on how this may be modified can be captured here.

**Comment by wbolster** [comment]
cross referencing https://github.com/bmallred/evil-colemak-minimal/issues/1#issuecomment-258565734

**Comment by wbolster** [comment]
i think i just had a brilliant idea. ;)

i use `f` quite a lot to jump to a character, but i almost never use `t` to jump "until" a character. the reason that `t` is not so useful is that i can use `a` or `i` as a next step after jumping to start editing before or after the character i jumped to. with `t` this does not make much sense.

(i use [evil-snipe](https://github.com/hlissner/evil-snipe) to spice it up but that's not really relevant for the issue at hand).

colemak `t` is at the qwerty `f` position, and colemak `f` is at the qwerty `e` position, and this is where it all comes together. here's the idea:

* colemak `t` (qwerty `f`) will do what `f` does in vim: jump to char. same position as on qwerty.
* colemak `f` (qwerty `e`) will jump to end of word. same position as on qwerty.
* colemak `j` (qwerty `y`) is hard to reach, and with my other colemak bindings this was used to jump to end of word. since that is now elsewhere, i can put the almost never used "jump until character" (`t` in vim) to this hard to reach position.

hopefully i made it clear. what do you think?

**Comment by bmallred** [comment]
Actually that sounds great. Last night I was looking at the layouts and was going to suggest some substitution based on least used keys. For me ```s``` and ```t``` fit that criteria as well :-)

I like the the new positioning of ```t``` as well because it is highly used.

Going to have to check out this evil-snipe package. If it works across frames it would make life so pleasant. Sometimes I work with ```M-x new-frame``` so I can share buffers across multiple monitors. Unfortunately it means I have to switch my navigation between evil-mode to i3 depending on where I want to focus.

**Comment by wbolster** [comment]
you should check out [avy](https://github.com/abo-abo/avy) and its evil wrapper [evil-easymotion](https://github.com/PythonNut/evil-easymotion). i never use multiple frames at the same time, but i just noticed that the `avy-all-windows`/`avy-all-windows-alt` customizable options (`M-x customize-group RET avy RET`) can be configured to consider all frames (one is the normal behaviour, the `alt` one is when a prefix argument is used).

**Comment by wbolster** [comment]
i have implemented this in a clean way, and have also expanded and rewritten the readme with more diagrams and design rationale:

https://github.com/wbolster/evil-colemak-basics/

feedback welcome :)
