### ISSUE TITLE
add example .vimrc for people who have memorized this keymapping

### ISSUE THREAD

**Issue by tommy-mor** [wbolster/evil-colemak-basics#6]
I prefer to use emacs with this package, but sometimes I must use vim.
I think a nice convenience to add to this package would be a .vimrc file that adds the same keybindings for ease of transitioning.

I have a basic one here, I'm not sure it's correct
https://gist.github.com/tommy-mor/77edead23a6040caa5aaa5f2a0714360

**Comment by wbolster** [comment]
oh wow. thanks for writing this. the first few words already made my day :laughing: 

> I prefer to use emacs with this package

years ago, i wrote this mutant ninja frankenstein turtle mix of vim and colemak on top of emacs-evil with some pretty nontrivial keybindings... and bothered to publish/describe it, but mostly for myself and for :nerd_face: points.

i use it extensively my self, of course, but i always thought i must've been the only one in the world, because i kept telling myself... looking at that README, would anyone be inclined to think ‘ah yeah sure makes total sense let me rewire my brain for that?’

WELL, long live the internet! :+1: 

anyway, that said, this package drew inspiration from https://github.com/insidewhy/colemak (see https://github.com/wbolster/evil-colemak-basics#credits) which also includes some vim configuration.

is your vimrc similar/identical to that?

of course, happy to include a vimrc snippet in this repository, with a note in the readme pointing to it. pull requests welcome!

**Comment by wbolster** [comment]
fixed by #7
